# NumPy

In [1]:
# NumPy - Numerical Python 
# - Python library for working with arrays
# - Also has functions for working in linear algebra, fourier tranform and matrics
# In Python, List are slow in processing. but Numpy array is faster than lists
# array object in numpy is called ndarray
import numpy as np
array_1 = np.array([1,2,3,4,5])
print(array_1)

[1 2 3 4 5]


In [2]:
print(np.__version__)

1.19.2


In [3]:
print(type(array_1)) # Type of array
print(array_1[0])

<class 'numpy.ndarray'>
1


In [4]:
print(array_1.ndim) # Dimensions of array

1


In [5]:
array_2 = np.array([1,2,3,4,5],ndmin=5) # ndmin -> Number of dimensions
print(array_2)
print(array_2.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [6]:
array_3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_3.ndim)
print(array_3[1,0])

2
6


In [7]:
array_4 = np.array([
    [[1,2,3,4]],
    [[4,5,6,7]],
    [[8,9,10,11]]
])
print(array_4.ndim)
print(array_4)

3
[[[ 1  2  3  4]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [8]:
array_5 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array_5[1:6])
print(array_5[-3:-1])
print(array_5[1:5:2]) # [start:end:step]
print(array_5[::2])

[2 3 4 5 6]
[8 9]
[2 4]
[1 3 5 7 9]


In [9]:
array_6 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_6[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [10]:
# Data Type in Numpy
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''
print(array_6.dtype)

int32


In [11]:
array_7 = np.array([1,2,3,4,5],dtype='S')
print(array_7)
print(array_7.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [12]:
# Convert Data Type
array_8 = array_7.astype('i')
print(array_8)
print(array_8.dtype)

[1 2 3 4 5]
int32


In [13]:
# Numpy Copy and View
array_9 = array_8.copy() # Copy creates new memory
array_8[2] = 10
print(array_9)
print(array_8)
array_10 = array_8.view() # View points same memory location
array_8[2] = 12
print(array_10)
print(array_8)

[1 2 3 4 5]
[ 1  2 10  4  5]
[ 1  2 12  4  5]
[ 1  2 12  4  5]


In [14]:
print(array_9.base)  # Return None if array owns the data
print(array_10.base) # Return original array

None
[ 1  2 12  4  5]


In [15]:
print(array_8.shape) # Shape for array () 
print(array_6.shape) # Shape - 2 dimensions and 5 elements in each dimensions

(5,)
(2, 5)


In [16]:
array_11 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_12 = array_11.reshape(4,3)  # 1 dimensions to 2 dimesnions - 4 arrays with 3 elememnts each
print(array_12)
array_13 = array_11.reshape(2,3,2) # 1 dimenstion to 3 dimenstions - 2 array contains 3 arrays with 2 elements each
print(array_13)
array_14 = array_12.reshape(-1)    # 2 dimensions to 1 dimesnion 
print(array_14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
# Array Iteration 
for i in array_12:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [18]:
for i in array_12:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
# nditer() is a helping function that can be used from very basic to very advanced iterations.
for i in np.nditer(array_13):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
for index, value in np.ndenumerate(array_11):
    print(index, value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [21]:
#Array Join
array_15 = np.array([1,2,3,4])
array_16 = np.array([5,6,7,8])
array_17 = np.concatenate((array_15, array_16))
print(array_17)
print('----------------------------------------------------')
array_15 = np.array([[1,2],[3,4]])
array_16 = np.array([[5,6],[7,8]])
array_17 = np.concatenate((array_15, array_16),axis=1)
print(array_17)
print('----------------------------------------------------')
array_15 = np.array([1,2,3,4])
array_16 = np.array([5,6,7,8])
array_17 = np.stack((array_15, array_16),axis=1)
print(array_17)
print('----------------------------------------------------')
array_15 = np.array([[1,2],[3,4]])
array_16 = np.array([[5,6],[7,8]])
array_17 = np.stack((array_15, array_16),axis=1)
print(array_17)
print('----------------------------------------------------')
array_15 = np.array([[1,2],[3,4]])
array_16 = np.array([[5,6],[7,8]])
array_17 = np.hstack((array_15, array_16))            # Stakcing along rows
print(array_17)
print('----------------------------------------------------')
array_15 = np.array([[1,2],[3,4]])
array_16 = np.array([[5,6],[7,8]])
array_17 = np.vstack((array_15, array_16))            # Stacking along columns
print(array_17)
print('----------------------------------------------------')
array_15 = np.array([[1,2],[3,4]])
array_16 = np.array([[5,6],[7,8]])
array_17 = np.dstack((array_15, array_16))            # Stacking along height(depth)
print(array_17)
print('----------------------------------------------------')

[1 2 3 4 5 6 7 8]
----------------------------------------------------
[[1 2 5 6]
 [3 4 7 8]]
----------------------------------------------------
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
----------------------------------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
----------------------------------------------------
[[1 2 5 6]
 [3 4 7 8]]
----------------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------------------------------------------------
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
----------------------------------------------------


In [22]:
# Splitting Array
array_18 = np.array([1,2,3,4,5,6])
array_19 = np.array_split(array_18,3,axis=0)
print(array_19)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [23]:
array_19 = np.hsplit(array_12,3)
print(array_19)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [24]:
# Array Search
x = np.where(array_18 == 4)  # Index of matching element
print(x)

(array([3], dtype=int64),)


In [25]:
x = np.where(array_18%2 == 0)
print(x)

(array([1, 3, 5], dtype=int64),)


In [26]:
x = np.searchsorted(array_18,4) # Index of matching element
print(x) 
x = np.searchsorted(array_18,4,side="right") # Right most Index 
print(x) 
x = np.searchsorted(array_18,[11,12,13]) # Index where value should be inserted
print(x)

3
4
[6 6 6]


In [27]:
# Array Sort
array_20 = np.array([1,0,4,2,5,3])
print(np.sort(array_20))

[0 1 2 3 4 5]


In [28]:
# Array Filter
array_21 = np.array([1,2,3,4])

x = [True, False, True, False]
print(array_21[x])

[1 3]


In [29]:
filter_array_21 = array_21 > 2
print(array_21[filter_array_21])

[3 4]
