# NumPy ufuncs

In [1]:
# ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.
# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
# Vectorization - Converting iterative statements into a vector based operation. It is faster as modern CPUs 
#                 are optimized for such operations.
# Create ufuncs -
#     To create you own ufunc, you have to define a function, like you do with normal functions in Python, 
#     then you add it to your NumPy ufunc library with the frompyfunc() method.
#     The frompyfunc() method takes the following arguments:
#         1. function - the name of the function.
#         2. inputs - the number of input arguments (arrays).
#         3. outputs - the number of output arrays
import numpy as np
def add_fun(x,y):
    return x + y
add_fun = np.frompyfunc(add_fun,2,1)
print(add_fun([1,2,3,4],[5,6,7,8]))
print(type(np.add))

[6 8 10 12]
<class 'numpy.ufunc'>


In [2]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,1])
print(np.add(array_1,array_2))
print(np.subtract(array_2,array_1))
print(np.multiply(array_1,array_2))
print(np.divide(array_2,array_1))
print(np.power(array_1,array_2))
print(np.mod(array_1,array_2))
print(np.remainder(array_1,array_2))
print(np.divmod(array_1,array_2)) # Quotient and Mod
print(np.absolute(array_1))

[ 7  9 11 13  6]
[ 5  5  5  5 -4]
[ 6 14 24 36  5]
[6.         3.5        2.66666667 2.25       0.2       ]
[     1    128   6561 262144      5]
[1 2 3 4 0]
[1 2 3 4 0]
(array([0, 0, 0, 0, 5], dtype=int32), array([1, 2, 3, 4, 0], dtype=int32))
[1 2 3 4 5]


In [3]:
# Rounding
array_3 = np.array([1.456,2.12,3.56,4.99])
print(np.trunc(array_3))
print(np.fix(array_3))
print(np.around(array_3,1))
print(np.floor(array_3))
print(np.ceil(array_3))

[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.5 2.1 3.6 5. ]
[1. 2. 3. 4.]
[2. 3. 4. 5.]


In [4]:
# Logs
array_4 = np.array([1,2,3,4])
print(np.log2(array_4))
print(np.log10(array_4))
print(np.log(array_4))   # Natural log (base e)

[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]
[0.         0.69314718 1.09861229 1.38629436]


In [5]:
# Summations
# Addition is done between two arguments whereas summation happens over n elements.
array_5 = np.array([1,2,3,4])
array_6 = np.array([5,6,7,8])
print(np.sum([array_5,array_6]))
print(np.add(array_5,array_6))
print(np.sum([array_5,array_6],axis=1))
print(np.cumsum(array_5))

36
[ 6  8 10 12]
[10 26]
[ 1  3  6 10]


In [6]:
# Product - Product of the elements in an array.
array_7 = np.arange(1,5)
array_8 = np.arange(5,9)
print(array_7,array_8)
print(np.prod(array_7))
print(np.prod([array_7, array_8]))
print(np.prod([array_7, array_8],axis=1))
print(np.cumprod(array_7))

[1 2 3 4] [5 6 7 8]
24
40320
[  24 1680]
[ 1  2  6 24]


In [7]:
# Difference - A discrete difference means subtracting two successive elements.
array_9 = np.array([10,5,15,20])
print(np.diff(array_9))
print(np.diff(array_9,n=2)) # We can perform this operation repeatedly by giving parameter n

[-5 10  5]
[15 -5]


In [8]:
# LCM (Lowest Common Multiple)
num_1 = 4
num_2 = 6
print(np.lcm(num_1,num_2))
#Returns: 12 because that is the lowest common multiple of both numbers (4*3=12 and 6*2=12).

array_10 = np.arange(1,5)
print(np.lcm.reduce(array_10))

12
12


In [9]:
# GCD (Greatest Common Denominator)
num_1 = 4
num_2 = 6
print(np.gcd(num_1,num_2))

print(np.gcd.reduce(array_10))
# The reduce() method will use the ufunc, in this case the gcd() function, on each element, 
# and reduce the array by one dimension.

2
1


In [10]:
# Trigonometric - take values in radians and produce the corresponding sin, cos and tan values.

print(np.sin(45))
print(np.tan(45))
print(np.cos(45))

# Degree to radians
print(np.deg2rad(90))
print(np.rad2deg(np.pi/2))

# Finding Angles - Produce radian values
print(np.arcsin(1.0))
print(np.arctan(1.0))
print(np.arccos(1.0))

# Hypotenues
base = 3 # Base
perp = 4 # Perpendicular
print(np.hypot(base,perp))

# Hyperbolic
print(np.sinh(np.pi/2))
print(np.tanh(np.pi/2))
print(np.cosh(np.pi/2))

# Hyperbolic - Finding Angle
print(np.arcsinh(1.0))
print(np.arctanh(0.5))
print(np.arccosh(1.0))

0.8509035245341184
1.6197751905438615
0.5253219888177297
1.5707963267948966
90.0
1.5707963267948966
0.7853981633974483
0.0
5.0
2.3012989023072947
0.9171523356672744
2.5091784786580567
0.881373587019543
0.5493061443340549
0.0


In [11]:
# Set Operations - collection of unique elements.
array_11 = np.array([1,1,2,3,4,3,3,3,3,4,5,5,5,5,1,1,1,])
print(np.unique(array_11))

[1 2 3 4 5]


In [12]:
array_12 = np.array([1,2,3,4,5])
array_13 = np.array([4,5,6,7,8])
print(np.union1d(array_12,array_13))
print(np.intersect1d(array_12,array_13,assume_unique=True))
print(np.setdiff1d(array_12,array_13,assume_unique=True))
print(np.setxor1d(array_12,array_13,assume_unique=True)) #Symmetric Difference

[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]
[1 2 3 6 7 8]
